/*
 * ForClase.java
 *
 * Created on 20 de junio de 2008, 07:11 PM
 */

package Presentacion;

import Estructura.Atributo;
import Estructura.CONST;
import Estructura.Metodo;
import Grafica.ClaseGrafica;
import Grafica.Diagrama;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author  Sandrita
 */
public class ForClase extends javax.swing.JDialog {
    
    /** Creates new form ForClase */
    private Diagrama diagrama;
    private ClaseGrafica clase;
    
    private LinkedList<Atributo> listaA;
    private LinkedList<Metodo> listaM;
    
    private LinkedList<String> listaAElim;
    private LinkedList<String> listaMElim;    
    
    private DefaultListModel modeloListaA;
    private DefaultListModel modeloListaM;
    
    public ForClase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ForClase( java.awt.Frame parent, boolean modal, ClaseGrafica clase,
                     Diagrama diagrama ) {
        super(parent, modal);
        initComponents();
        
        this.diagrama=diagrama;
        this.clase=clase; 
        this.listaA=new LinkedList<Atributo>();
        this.listaM=new LinkedList<Metodo>();
        
        this.listaAElim=new LinkedList<String>();
        this.listaMElim=new LinkedList<String>();
        
        this.modeloListaA=new DefaultListModel();
        this.modeloListaM=new DefaultListModel();
        
        this.inicializar();
    }    
    
    public void inicializar(){
        String nombre=this.clase.getNombre();        
        this.tNombre.setText( nombre );
        
        this.inicializarModeloAtributo( clase.obtenerLAtributos() );
        this.inicializarModeloMetodo( clase.obtenerLMetodos() );
    }
    
    public void inicializarModeloAtributo( LinkedList<Atributo> lista ){
        for (int i = 0; i < lista.size(); i++) {
            Atributo atributo = lista.get(i);
            modeloListaA.addElement( atributo.toStringGrafico() );
        }
        this.lAtributo.setModel( modeloListaA );
    }
    
    public void inicializarModeloMetodo( LinkedList<Metodo> lista ){
        for (int i = 0; i < lista.size(); i++) {
            Metodo metodo = lista.get(i);
            modeloListaM.addElement( metodo.toStringGrafico() );
        }
        this.lMetodo.setModel( modeloListaM );
    }    
    
   
    public void addAtributoLista( Atributo atributo ){
        modeloListaA.addElement( atributo.toStringGrafico() );
        this.lAtributo.setModel( modeloListaA );
    }
    
    public void addMetodoLista( Metodo metodo ){
        modeloListaM.addElement( metodo.toStringGrafico() );
        this.lMetodo.setModel( modeloListaM );
    }
    
   
    public void cargarMetodos( ){
        for (int i = 0; i < listaM.size(); i++) {
            Metodo metodo = listaM.get(i);
            this.clase.adicionarMetodo( metodo );
        }
        this.listaM=new LinkedList<Metodo>();
    }
    
    public void cargarAtributos( ){
        for (int i = 0; i < listaA.size(); i++) {
            Atributo atributo = listaA.get(i);
            this.clase.adicionarAtributo( atributo );
        }
        this.listaA=new LinkedList<Atributo>();
    }
    
    
    public void eliminarMetodos( ){
        for (int i = 0; i < listaMElim.size(); i++) {
            int index = Integer.parseInt( listaMElim.get(i) );
            this.clase.eliminarMetodo( index );                      
        }
        this.listaMElim=new LinkedList<String>();
    }
    
    public void eliminarAtributos( ){
        for (int i = 0; i < listaAElim.size(); i++) {
            int index = Integer.parseInt( listaAElim.get(i) );
            this.clase.eliminarAtributo( index );
        }
        this.listaAElim=new LinkedList<String>();
    }    
    
    private void ponerNombre(){
        if( !tNombre.getText().equals("") ){
            String nombre=tNombre.getText();
            this.clase.setNombre(nombre);
            
            if( rbAbstract.isSelected() )
                this.clase.getClase().setTipo( "abstract");
            if( rbFinal.isSelected() )
                this.clase.getClase().setTipo( "abstract");
            if( rbInterface.isSelected() )
                this.clase.getClase().setTipo( "interface");            
        }
        else
            JOptionPane.showMessageDialog( this, "Introdusca el nombre de la Clase", "Clase", JOptionPane.ERROR_MESSAGE); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGrupo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pGeneral = new javax.swing.JPanel();
        tNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbInterface = new javax.swing.JRadioButton();
        rbAbstract = new javax.swing.JRadioButton();
        rbFinal = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rbCPrivate = new javax.swing.JRadioButton();
        rbCPublic = new javax.swing.JRadioButton();
        rbCProtected = new javax.swing.JRadioButton();
        bGOK = new javax.swing.JButton();
        bGCancelar = new javax.swing.JButton();
        pAtributo = new javax.swing.JPanel();
        tNAtributo = new javax.swing.JTextField();
        cbTipoAtributo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rbAPrivate = new javax.swing.JRadioButton();
        rbAPublic = new javax.swing.JRadioButton();
        rbAProtected = new javax.swing.JRadioButton();
        bAOk = new javax.swing.JButton();
        bACancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lAtributo = new javax.swing.JList();
        bAddAtributo = new javax.swing.JButton();
        bElimAtributo = new javax.swing.JButton();
        pMetodo = new javax.swing.JPanel();
        tNMetodo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbRetorno = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        rbMPrivate = new javax.swing.JRadioButton();
        rbMPublic = new javax.swing.JRadioButton();
        rbMProtected = new javax.swing.JRadioButton();
        bMOk = new javax.swing.JButton();
        bMCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lMetodo = new javax.swing.JList();
        bAddMetodo = new javax.swing.JButton();
        bElimMetodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));

        rbInterface.setText("interface");

        rbAbstract.setText("abstract");

        rbFinal.setText("final");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFinal)
                    .addComponent(rbAbstract)
                    .addComponent(rbInterface))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbInterface)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAbstract)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbFinal))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Acceso"));

        rbCPrivate.setText("private");
        rbCPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCPrivateActionPerformed(evt);
            }
        });

        rbCPublic.setSelected(true);
        rbCPublic.setText("public");

        rbCProtected.setText("protected");
        rbCProtected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCProtectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCProtected)
                    .addComponent(rbCPrivate)
                    .addComponent(rbCPublic))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCPrivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCPublic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbCProtected)
                .addContainerGap())
        );

        bGOK.setMnemonic('O');
        bGOK.setText("OK");
        bGOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGOKActionPerformed(evt);
            }
        });

        bGCancelar.setMnemonic('C');
        bGCancelar.setText("Cancelar");
        bGCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pGeneralLayout = new javax.swing.GroupLayout(pGeneral);
        pGeneral.setLayout(pGeneralLayout);
        pGeneralLayout.setHorizontalGroup(
            pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bGOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pGeneralLayout.setVerticalGroup(
            pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGeneralLayout.createSequentialGroup()
                .addGroup(pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGeneralLayout.createSequentialGroup()
                        .addGroup(pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pGeneralLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(pGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pGeneralLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGeneralLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bGOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bGCancelar)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", pGeneral);

        cbTipoAtributo.setEditable(true);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Tipo:");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Acceso"));

        rbAPrivate.setSelected(true);
        rbAPrivate.setText("private");
        rbAPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAPrivateActionPerformed(evt);
            }
        });

        rbAPublic.setText("public");

        rbAProtected.setText("protected");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAPrivate)
                    .addComponent(rbAPublic)
                    .addComponent(rbAProtected))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(rbAPrivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAPublic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAProtected))
        );

        bAOk.setText("OK");
        bAOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAOkActionPerformed(evt);
            }
        });

        bACancelar.setText("Cancelar");
        bACancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bACancelarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setViewportView(lAtributo);

        bAddAtributo.setText("Adicionar");
        bAddAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddAtributoActionPerformed(evt);
            }
        });

        bElimAtributo.setText("Eliminar");
        bElimAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bElimAtributoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bElimAtributo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(bAddAtributo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bAddAtributo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bElimAtributo)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pAtributoLayout = new javax.swing.GroupLayout(pAtributo);
        pAtributo.setLayout(pAtributoLayout);
        pAtributoLayout.setHorizontalGroup(
            pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAtributoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pAtributoLayout.createSequentialGroup()
                        .addGroup(pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoAtributo, 0, 164, Short.MAX_VALUE)
                            .addComponent(tNAtributo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bAOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bACancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        pAtributoLayout.setVerticalGroup(
            pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtributoLayout.createSequentialGroup()
                .addGroup(pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAtributoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tNAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pAtributoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbTipoAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pAtributoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bAOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bACancelar))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jTabbedPane1.addTab("Atributos", pAtributo);

        jLabel4.setText("Nombre:");

        jLabel5.setText("Retorno:");

        cbRetorno.setEditable(true);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Acceso"));

        rbMPrivate.setText("private");
        rbMPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMPrivateActionPerformed(evt);
            }
        });

        rbMPublic.setSelected(true);
        rbMPublic.setText("public");

        rbMProtected.setText("protected");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMPrivate)
                    .addComponent(rbMPublic)
                    .addComponent(rbMProtected))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(rbMPrivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMPublic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMProtected))
        );

        bMOk.setText("OK");
        bMOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMOkActionPerformed(evt);
            }
        });

        bMCancelar.setText("Cancelar");
        bMCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMCancelarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setViewportView(lMetodo);

        bAddMetodo.setText("Adicionar");
        bAddMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddMetodoActionPerformed(evt);
            }
        });

        bElimMetodo.setText("Eliminar");
        bElimMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bElimMetodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bElimMetodo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(bAddMetodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bAddMetodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bElimMetodo)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pMetodoLayout = new javax.swing.GroupLayout(pMetodo);
        pMetodo.setLayout(pMetodoLayout);
        pMetodoLayout.setHorizontalGroup(
            pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMetodoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pMetodoLayout.createSequentialGroup()
                        .addGroup(pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRetorno, 0, 162, Short.MAX_VALUE)
                            .addComponent(tNMetodo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bMOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bMCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        pMetodoLayout.setVerticalGroup(
            pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMetodoLayout.createSequentialGroup()
                .addGroup(pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMetodoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tNMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pMetodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pMetodoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bMOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bMCancelar))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jTabbedPane1.addTab("Metodos", pMetodo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tNombreActionPerformed

    private void rbCPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCPrivateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_rbCPrivateActionPerformed

    private void rbAPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAPrivateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_rbAPrivateActionPerformed

    private void rbCProtectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCProtectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCProtectedActionPerformed

    private void rbMPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMPrivateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_rbMPrivateActionPerformed

    private void bGCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bGCancelarActionPerformed

    private void bGOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGOKActionPerformed
        // TODO add your handling code here:
        this.ponerNombre();
        
        this.eliminarAtributos();
        this.cargarAtributos();
        
        this.eliminarMetodos();
         this.cargarMetodos(); 
        
        this.diagrama.adicionarFigura( clase );
        //System.out.println( this.clase.getClase().toString() );
        this.dispose();
    }//GEN-LAST:event_bGOKActionPerformed

    private void bAOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAOkActionPerformed
        // TODO add your handling code here:
        this.ponerNombre();
        
        this.eliminarAtributos();
        this.cargarAtributos();
        
        this.eliminarMetodos();
        this.cargarMetodos();   
        
        this.diagrama.adicionarFigura( clase );        
        this.dispose();
        
    }//GEN-LAST:event_bAOkActionPerformed

    private void bAddAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddAtributoActionPerformed
        // TODO add your handling code here:
        if( !tNAtributo.getText().equals("") ){
            String nombre=tNAtributo.getText();
            String tipo=cbTipoAtributo.getSelectedItem().toString();
            
            int acceso=0;
            if( rbAPrivate.isSelected() )
               acceso=CONST.V_PRIVATE;
            if( rbAPublic.isSelected() )
               acceso=CONST.V_PUBLIC; 
            if( rbAProtected.isSelected() )
               acceso=CONST.V_PROTECTED; 
            
            Atributo atributo=new Atributo(nombre, tipo, acceso);
            
            listaA.add( atributo );            
            this.addAtributoLista( atributo );
            
            DefaultComboBoxModel modelo=(DefaultComboBoxModel)cbTipoAtributo.getModel();
            int index=modelo.getIndexOf( tipo );
            if( index<0 )
                modelo.addElement( tipo );
            cbTipoAtributo.setModel(modelo);                          
        }
        else
            JOptionPane.showMessageDialog( this, "Introdusca el nombre del Atributo", "Clase", JOptionPane.ERROR_MESSAGE);            
    }//GEN-LAST:event_bAddAtributoActionPerformed

    private void bACancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bACancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bACancelarActionPerformed

    private void bElimAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bElimAtributoActionPerformed
        // TODO add your handling code here:
        int pos=lAtributo.getSelectedIndex();
        this.modeloListaA.remove( pos );               
        this.lAtributo.setModel( modeloListaA );
                
        this.listaAElim.add( "" + pos );
        
        if( pos<listaA.size() )
            this.listaA.remove( pos );          
    }//GEN-LAST:event_bElimAtributoActionPerformed

    private void bMOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMOkActionPerformed
        // TODO add your handling code here:
        this.ponerNombre();
        
        this.eliminarMetodos();
        this.cargarMetodos();
        
        this.eliminarAtributos();
        this.cargarAtributos();        
        
        this.diagrama.adicionarFigura( clase );
        this.dispose();
    }//GEN-LAST:event_bMOkActionPerformed

    private void bMCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bMCancelarActionPerformed

    private void bAddMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddMetodoActionPerformed
        // TODO add your handling code here:
        if( !tNMetodo.getText().equals("") ){
            String nombre=tNMetodo.getText();
            String retorno=cbRetorno.getSelectedItem().toString();
            
            int acceso=0;
            if( rbMPrivate.isSelected() )
               acceso=CONST.V_PRIVATE;
            if( rbMPublic.isSelected() )
               acceso=CONST.V_PUBLIC; 
            if( rbMProtected.isSelected() )
               acceso=CONST.V_PROTECTED; 
            
            Metodo metodo=new Metodo(nombre, retorno, acceso);
            
            listaM.add( metodo);            
            this.addMetodoLista( metodo );
            
            DefaultComboBoxModel modelo=(DefaultComboBoxModel)cbRetorno.getModel();
            int index=modelo.getIndexOf( retorno );
            if( index<0 )
                modelo.addElement( retorno );
            cbRetorno.setModel(modelo);             
        }
        else
            JOptionPane.showMessageDialog( this, "Introdusca el nombre del Metodo", "Clase", JOptionPane.ERROR_MESSAGE);     
    }//GEN-LAST:event_bAddMetodoActionPerformed

    private void bElimMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bElimMetodoActionPerformed
        // TODO add your handling code here:        
        int pos=lMetodo.getSelectedIndex();
        this.modeloListaM.remove( pos );               
        this.lMetodo.setModel( modeloListaM );
        
        this.listaMElim.add( "" + pos ); 
        
        if( pos<listaM.size() )
            this.listaM.remove( pos );          
    }//GEN-LAST:event_bElimMetodoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ForClase dialog = new ForClase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bACancelar;
    private javax.swing.JButton bAOk;
    private javax.swing.JButton bAddAtributo;
    private javax.swing.JButton bAddMetodo;
    private javax.swing.JButton bElimAtributo;
    private javax.swing.JButton bElimMetodo;
    private javax.swing.JButton bGCancelar;
    private javax.swing.JButton bGOK;
    private javax.swing.ButtonGroup bGrupo;
    private javax.swing.JButton bMCancelar;
    private javax.swing.JButton bMOk;
    private javax.swing.JComboBox cbRetorno;
    private javax.swing.JComboBox cbTipoAtributo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList lAtributo;
    private javax.swing.JList lMetodo;
    private javax.swing.JPanel pAtributo;
    private javax.swing.JPanel pGeneral;
    private javax.swing.JPanel pMetodo;
    private javax.swing.JRadioButton rbAPrivate;
    private javax.swing.JRadioButton rbAProtected;
    private javax.swing.JRadioButton rbAPublic;
    private javax.swing.JRadioButton rbAbstract;
    private javax.swing.JRadioButton rbCPrivate;
    private javax.swing.JRadioButton rbCProtected;
    private javax.swing.JRadioButton rbCPublic;
    private javax.swing.JRadioButton rbFinal;
    private javax.swing.JRadioButton rbInterface;
    private javax.swing.JRadioButton rbMPrivate;
    private javax.swing.JRadioButton rbMProtected;
    private javax.swing.JRadioButton rbMPublic;
    private javax.swing.JTextField tNAtributo;
    private javax.swing.JTextField tNMetodo;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
    
}
